### ISSUE TITLE
unknown recurrence

### ISSUE THREAD

**Issue by michael-nelson** [ronnieholm/SPCalendarRecurrenceExpander#1]
Hello,

I get the error 'Unknown recurrence'. I think this is what is causing the issue: 

<recurrence><rule><firstDayOfWeek>su</firstDayOfWeek><repeat><monthlyByDay mo='TRUE' weekdayOfMonth='second' monthFrequency='1' /></repeat><windowEnd>2016-07-17T06:59:00Z</windowEnd></rule></recurrence>

Any ideas?

Thanks,
Mike

**Comment by michael-nelson** [comment]
It looks like it didn't print the rest of the issue. I will attach an image instead ...

![error](https://cloud.githubusercontent.com/assets/13736101/9180482/a25ca448-3f57-11e5-8372-d536c4ac99be.PNG)

**Comment by ronnieholm** [comment]
Thank you for taking the time to report an issue.

Through the UI, I've created a recurrence appointment resulting in XML similar to what you provided. It seems to expand correctly.

My guess is you have some setup not covered by the recurrence XML.

Can you provide me with the exact repro steps? How exactly do you create the appointment through the UI?

**Comment by michael-nelson** [comment]
Hello,

I appreciate your help. I found out that when I create the recurring event through the Sharepoint site, everything works fine. But, when I duplicate the same steps through Outlook on my local machine, I get the error.

This doesn’t work…


[cid:image001.png@01D0D432.05C4A0D0]

<recurrence><rule><firstDayOfWeek>su</firstDayOfWeek><repeat><monthlyByDay tu='TRUE' weekdayOfMonth='second' monthFrequency='1' /></repeat><windowEnd>2016-05-11T06:59:00Z</windowEnd></rule></recurrence>

[cid:image002.png@01D0D432.8E8F1760]

This does work…
[cid:image003.png@01D0D433.CC655D00]

<recurrence><rule><firstDayOfWeek>su</firstDayOfWeek><repeat><monthlyByDay tu="TRUE" weekdayOfMonth="second" monthFrequency="1" /></repeat><windowEnd>2016-05-10T21:00:00Z</windowEnd></rule></recurrence>

[cid:image004.png@01D0D433.CC655D00]


Thanks,
Mike

**Comment by michael-nelson** [comment]
The only differences I saw in the objects of both are the description and metaInfo:

Works (created through Sharepoint)…

[cid:image005.png@01D0D436.79A05EA0]

[cid:image006.png@01D0D436.79A05EA0]

Doesn’t Work(created through Outlook desktop) …

[cid:image007.png@01D0D436.79A05EA0]

[cid:image008.png@01D0D436.79A05EA0]

Mike

From: Nelson, Michael
Sent: Tuesday, August 11, 2015 12:47 PM
To: 'ronnieholm/SPCalendarRecurrenceExpander'; ronnieholm/SPCalendarRecurrenceExpander
Subject: RE: [SPCalendarRecurrenceExpander] unknown recurrence (#1)

Hello,

I appreciate your help. I found out that when I create the recurring event through the Sharepoint site, everything works fine. But, when I duplicate the same steps through Outlook on my local machine, I get the error.

This doesn’t work…


[cid:image001.png@01D0D432.05C4A0D0]

<recurrence><rule><firstDayOfWeek>su</firstDayOfWeek><repeat><monthlyByDay tu='TRUE' weekdayOfMonth='second' monthFrequency='1' /></repeat><windowEnd>2016-05-11T06:59:00Z</windowEnd></rule></recurrence>

[cid:image002.png@01D0D432.8E8F1760]

This does work…
[cid:image011.png@01D0D436.79A05EA0]

<recurrence><rule><firstDayOfWeek>su</firstDayOfWeek><repeat><monthlyByDay tu="TRUE" weekdayOfMonth="second" monthFrequency="1" /></repeat><windowEnd>2016-05-10T21:00:00Z</windowEnd></rule></recurrence>

[cid:image012.png@01D0D436.79A05EA0]


Thanks,
Mike

**Comment by ronnieholm** [comment]
Github filters out your images.

I don't believe the issue is with the XML you provided, but with one of the other key/value pairs of the list item which SharePoint uses to represent the recurrence.

Could you provide the values for the following keys for a failing appoinment: 
- fRecurrence
- EventType
- MasterSeriesItemID
- RecurrenceData
- RecurrenceID

**Comment by michael-nelson** [comment]
*   fRecurrence
True

  *   EventType
1

  *   MasterSeriesItemID
null

  *   RecurrenceData
<recurrence><rule><firstDayOfWeek>su</firstDayOfWeek><repeat><monthlyByDay tu='TRUE' weekdayOfMonth='second' monthFrequency='1' /></repeat><windowEnd>2016-05-11T06:59:00Z</windowEnd></rule></recurrence>

  *   RecurrenceID
Null

  *   Description (null in the one that works)
<div dir="LTR"></div>

  *   MetaInfo (null in the one that works)
vti_encoding:SR|utf8-nl
FollowUp:SW|
vti_versionhistory:SW|de97ebfb2cab394bb8907df29fbd9a71:2,f29829fb3ac7514c8b40edeab918c196:3
vti_clientversion:SW|3
BusyStatus:SW|2
Categories:SW|
Priority:SW|0
ReplicationID:SW|{E0A890B7-1694-4178-B768-F3ABB296279B}
vti_externalversion:IW|2
IntendedBusyStatus:SW|-1
­­

**Comment by michael-nelson** [comment]
![doesn t work description](https://cloud.githubusercontent.com/assets/13736101/9213025/1ce9ed74-4043-11e5-9329-3397e4700c73.png)

**Comment by ronnieholm** [comment]
Parsing recurrence data fails because it contains ' instead of " characters. It appears Outlook creates appointments using single tick whereas SharePoint uses double tick.

**Comment by ronnieholm** [comment]
Please grap version 1.0.1 from NuGet.

**Comment by michael-nelson** [comment]
Thank you. Your update is working great. I appreciate you getting around to this so quickly.

**Comment by michael-nelson** [comment]
I found another possible issue. I get the error: Exception of type 'System.Collections.Generic.KeyNotFoundException' was thrown. This seems to happen when the user creates a recurrence event with: daily, every weekday, start date, end date. I can fix the problem if I change the daily/every weekday to weekly and select the weekdays. 

![every weekday recurrence error](https://cloud.githubusercontent.com/assets/13736101/11258464/1915cef2-8e0e-11e5-9036-ce40679c8afd.PNG)

**Comment by ronnieholm** [comment]
I copied your screen settings, but no exception on my end. 

I should include a routine to extract all the key/value pairs representing a recurrence event so it's easier to post a bug report.

**Comment by michael-nelson** [comment]
Maybe it has something to do with the edit to your code that I made; I had some issues with users creating events before the time change, but the event occurred after the time change. I also had a strange issue with all day event times. The below code fixed those issues for me.

            List<Dictionary<string, object>> partialList = new List<Dictionary<string, object>>();
            var collapsedAppointments = items.ToList().Select(i => i.FieldValues).ToList();

            for (int i = 0; i < collapsedAppointments.Count; i++)
           //     for (int i = 0; i < 400; i++)
                {
                var start = collapsedAppointments[i]["EventDate"].ToString();
                var end = collapsedAppointments[i]["EndDate"].ToString();


                TimeZoneInfo timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
                DateTime calConvertedTime = TimeZoneInfo.ConvertTime(Convert.ToDateTime(collapsedAppointments[i]["EventDate"]), timeZoneInfo);
                var isCalDaylightSavings = timeZoneInfo.IsDaylightSavingTime(calConvertedTime);

                DateTime currentConvertedTime = TimeZoneInfo.ConvertTime(DateTime.Now, timeZoneInfo);
                var isCurrentDaylightSavings = timeZoneInfo.IsDaylightSavingTime(currentConvertedTime);

                TimeSpan oneHour = new TimeSpan(1, 0, 0);

 if (!isCalDaylightSavings && !start.Contains("12:00:00 AM"))                 {
                    start = Convert.ToDateTime(start).Subtract(oneHour).ToString();
                    end = Convert.ToDateTime(end).Subtract(oneHour).ToString();
                    collapsedAppointments[i]["EventDate"] = start;
                    collapsedAppointments[i]["EndDate"] = end;
                }

                if (start != end)
                    partialList.Add(collapsedAppointments[i]);
                else
                {
                    DateTime endDate = Convert.ToDateTime(collapsedAppointments[i]["EndDate"]);
                    DateTime newEndDate = endDate.AddMinutes(5);
                    collapsedAppointments[i]["EndDate"] = newEndDate;
                    partialList.Add(collapsedAppointments[i]);
                }
            }

**Comment by ronnieholm** [comment]
I don't quite understand your code (the motivation behind the changes). 
Are the timezone settings correct for your web (under Site Settings). Where're you located physically?

**Comment by michael-nelson** [comment]
Site Settings show ‘UTC-08:00 Pacific Time (US and Canada)’. I live 1 hour north of Los Angeles. I am also using the below code. And, we are using a plug in to pull the ical file the below code is creating to pull into Wordpress. Only after I added the code with the time setting info did the times match in both systems when the time change issue was happening.

Func<RecurrenceInstance, Appointment> toDomainObject = (ri =>
            {
                var a = collapsedAppointments.First(i => int.Parse(i["ID"].ToString()) == ri.Id);
                return new Appointment
                {
                    Id = ri.Id,
                    Title = (string)a["Title"],
                    Start = ri.Start,
                    End = ri.End,
                    Location = (string)a["Location"],
                    Description = (string)a["Description"],
                    Category = (string)a["Category"],
                   // UniqueId = a["UniqueId"].ToString(),
                    UniqueId = Guid.NewGuid().ToString(),
                    Created = (DateTime)a["Created"],
                    Modified = (DateTime)a["Modified"],
                    EventType = (int)a["EventType"]
                };
            });

            StringBuilder sb = new StringBuilder();

            sb.Append("BEGIN:VCALENDAR");
            sb.Append("\nPRODID:-//Google Inc//Google Calendar 70.9054//EN");
            sb.Append("\nVERSION:2.0");
            sb.Append("\nCALSCALE:GREGORIAN");
            sb.Append("\nMETHOD:PUBLISH");
            sb.Append("\nX-WR-CALNAME:districtCalendar@ouhsd.com");
            sb.Append("\nX-WR-TIMEZONE:America/Los_Angeles");
            sb.Append("\nX-WR-CALDESC:Important Dates and Events.");

            sb.Append("\nBEGIN:VTIMEZONE");

                sb.Append("\nTZID:America/Los_Angeles");
                sb.Append("\nX-LIC-LOCATION:America/Los_Angeles");

                sb.Append("\nBEGIN:DAYLIGHT"); // mar - nov
                sb.Append("\nTZOFFSETFROM:-0800"); // 0800
                sb.Append("\nTZOFFSETTO:-0700");   // 0700
                sb.Append("\nTZNAME:PDT");
                sb.Append("\nDTSTART:19700308T020000");
                sb.Append("\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU");
                sb.Append("\nEND:DAYLIGHT");

                sb.Append("\nBEGIN:STANDARD"); // nov - mar
                sb.Append("\nTZOFFSETFROM:-0700"); // 0700
                sb.Append("\nTZOFFSETTO:-0800");   // 0800
                sb.Append("\nTZNAME:PST");
                sb.Append("\nDTSTART:19701101T020000");
                sb.Append("\nRRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU");
                sb.Append("\nEND:STANDARD");

            sb.Append("\nEND:VTIMEZONE");

            var expandedAppointments = recurrenceInstances.Select(toDomainObject).ToList(); // error here may mean that a field was added to calendar info when creating event that my code doesn't deal with
            Calendar calendarObj = new Calendar();
            calendarObj.appointments = expandedAppointments;

**Comment by ronnieholm** [comment]
Are all the user's in the same timezone?

**Comment by michael-nelson** [comment]
Yes

**Comment by ronnieholm** [comment]
Did Daylight Saving Time change recently for your timezone? I'm wondering if you can pinpoint a specific event that made the expander break.

**Comment by michael-nelson** [comment]
Time change occurred beginning of November. We were still in October when someone created an event in November that had a time an hour off in our Wordpress site. Expander didn’t break, but I am not sure right now if it was your code, the ical code (the 2nd code I sent), or the plug-in that threw it off by an hour. I just edited your code to change it by an hour.

**Comment by michael-nelson** [comment]
It is that change that may be causing the key value error I just got recently.

**Comment by michael-nelson** [comment]
I will try and look into it more when I get a chance.

**Comment by ronnieholm** [comment]
Sounds like there's a few too many moving parts. You need to simplify, I think :)

**Comment by michael-nelson** [comment]
I appreciate the help. Next time this key exception occurs, I will try running your original code to see if it breaks or not.

**Comment by ronnieholm** [comment]
SharePoint stores date/time as UTC internally. That's why one has to pass the local timezone and whether Daylight Saving Time is in effect to the expander. The expander uses this information to convert the UTC date/times of appointments to local time before expanding. An appointment generally ends at 11:59pm (even though it isn't shown in the UI). Thus, if the correction isn't correct, wrong occurrences come out the other end (and perhaps internal errors happen during expansion).

https://github.com/ronnieholm/SPCalendarRecurrenceExpander/blob/master/Src/SPCalendarRecurrenceExpander/Expander.fs#L9

**Comment by ronnieholm** [comment]
I think I know what causes your issue and why we had trouble reproducing.

See issue #3
