### ISSUE TITLE
Date Time Parse

### ISSUE THREAD

**Issue by juand1313** [ronnieholm/SPCalendarRecurrenceExpander#11]
Dear Ronnieholm,

I'm trying to use your assembly, however, in the code line:

var recurrenceInstances = expander.Expand(collapsedAppointments);

I got a "FormatException; this string was not recognized as a valid DateTime" error.

I already tested the regional settings with Central America and US and Canada, creating a new site collection, and the error still shows up.

I used your example and one of my own and both throws the same error. I saw another similar issue where you stated that error never happened to you, maybe I'm missing something?

I hope you could help me

Thank you, best regards

**Comment by ronnieholm** [comment]
Could you run expander.Dump(collapsedAppointments) and provide me with the output?

**Comment by juand1313** [comment]
Hello Ronnieholm,

Here is the data you requested.

[[("ID", Some 49); ("EventDate", Some 30/8/2016 10:00:00 p. m.);
  ("EndDate", Some 25/5/2019 11:00:00 p. m.); ("Duration", Some 3600);
  ("fRecurrence", Some true); ("EventType", Some 1);
  ("MasterSeriesItemID", Some null); ("RecurrenceID", Some null);
  ("RecurrenceData",
   Some
     "<recurrence><rule><firstDayOfWeek>su</firstDayOfWeek><repeat><daily dayFrequency="1" /></repeat><repeatForever>FALSE</repeatForever></rule></recurrence>");
  ("fAllDayEvent", Some false)]]

The difference I notice from the previous closed issue, is the date format, dd/mm/yyyy in my case.

Thank you for your quick response.

**Comment by ronnieholm** [comment]
Do you know which string is invalid? It isn't clear from looking at the dump, is it?

**Comment by ronnieholm** [comment]
Could you provide me with the stack trace?
