### ISSUE TITLE
URL of expanded items missing

### ISSUE THREAD

**Issue by ujwalseli** [ronnieholm/SPCalendarRecurrenceExpander#15]
I am unable to retrieve the URL of expanded events. 'FileRef' property gives URL of the Series and not individual events. How to get the URL for each occurrence?

**Comment by ronnieholm** [comment]
Do you mean that you have appointments with attached files and you're attempting to get at those?

**Comment by ujwalseli** [comment]
Let me explain in detail. I created a Reoccurring event occurring every weekday, for 3 weeks. the URL of this event(series) is like this

Series URL
_**https://contoso.sharepoint.com/teams/contoso/Lists/MyTasks/DispForm.aspx?ID=3734**_ 

however if i go to my calendar and click on event for a particular day(created by the series above) the URL for that event will be like this
_**https://contoso.sharepoint.com/teams/contoso/Lists/MyTasks/DispForm.aspx?ID=3734.0.T2017-09-30T08:15:00Z**_

On editing this task, say %completion update the URL will change to
_**https://contoso.sharepoint.com/teams/contoso/Lists/MyTasks/DispForm.aspx?ID=ID=3743.1.3734**_


Now via CSOM I want to iterate through all the events  in the series and get URL for each event, the data returned from package doesn't seem to capture the URL anywhere. I can get/form the URL series but not 
for individual items as ID is same for all items in returned collection.

**Comment by ronnieholm** [comment]
I see. You're correct. The library doesn't support this requirement. To my knowledge, SharePoint has no public API for this. The URL generator would appear to be build into the calendar control itself.

**Comment by ujwalseli** [comment]
Alright, thanks for the information.
