### ISSUE TITLE
'Unable to Parse end' error while calling  expander.Expand

### ISSUE THREAD

**Issue by ujwalseli** [ronnieholm/SPCalendarRecurrenceExpander#17]
Description
--
I am facing this error while calling expander.Expand. i was able to zero down to the records which are causing this issue, however i am unable to identify the fields in records which are causing this. here is the raw data of one such record causing this issue. Can you help me identify the root cause?

**Record data**
--
+ |   | [0] | {[ContentTypeId,   0x0102004B17F3AE6037154AB1D979F750727D03]} | System.Collections.Generic.KeyValuePair<string,   object>
-- | -- | -- | -- | --
+ |   | [1] | {[Title, Quarterly review of Site Assignment document]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [2] | {[_ModerationComments, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [3] | {[File_x0020_Type, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [4] | {[Location, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [5] | {[EventDate, 11/1/2016 4:00:00 PM]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [6] | {[EndDate, 11/1/2016 5:00:00 PM]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [7] | {[Description, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [8] | {[fAllDayEvent, False]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [9] | {[fRecurrence, True]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [10] | {[WorkspaceLink, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [11] | {[EventType, 1]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [12] | {[UID, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [13] | {[RecurrenceID, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [14] | {[EventCanceled, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [15] | {[Duration, 3600]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [16] | {[RecurrenceData, Every 3 month(s) on the first Tuesday]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [17] | {[TimeZone, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [18] | {[XMLTZone, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [19] | {[MasterSeriesItemID, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [20] | {[Workspace, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [21] | {[ParticipantsPicker, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [22] | {[Category, (2) Category2]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [23] | {[FreeBusy, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [24] | {[Overbook, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [25] | {[Participants, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [26] | {[_x0025__x0020_Complete, 0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [27] | {[Assigned_x0020_To, Microsoft.SharePoint.Client.FieldUserValue[]]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [28] | {[Escalation, False]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [29] | {[Status, Not Started]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [30] | {[Reports_x0020_To, Microsoft.SharePoint.Client.FieldUserValue]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [31] | {[Actions, <div>Go to&#58; </div> |   |   |   |   |   |  
<div>&#160;</div> |   |   |   |   |   |   |   |  
<div><a   href="/Pages/SiteAssignments.aspx">https&#58;//contoso/sites/Pages/SiteAssignments.aspx</a></div> |   |   |   |   |   |  
<div>&#160;</div> |   |   |   |   |   |   |   |  
<div>Review   FTEs and Vendors assigned to each site and update as appropriate.</div> |   |   |   |   |   |  
<div>&#160;</div> |   |   |   |   |   |   |   |  
<div>To update send an email with   required changes to <a   href="mailto&#58;user@microsoft.com">user@microsoft.com</a>&#160;and   cc Ujwal</div>]} | System.Collections.Generic.KeyValuePair<string,   object> |   |   |   |   |   |  
+ |   | [32] | {[Related_x0020_To, N/A]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [33] | {[ID, 9804]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [34] | {[Modified, 6/28/2017 11:35:39 AM]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [35] | {[Created, 6/27/2017 6:27:53 PM]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [36] | {[Author, Microsoft.SharePoint.Client.FieldUserValue]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [37] | {[Editor, Microsoft.SharePoint.Client.FieldUserValue]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [38] | {[_HasCopyDestinations, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [39] | {[_CopySource, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [40] | {[owshiddenversion, 3]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [41] | {[WorkflowVersion, 1]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [42] | {[_UIVersion, 512]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [43] | {[_UIVersionString, 1.0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [44] | {[Attachments, False]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [45] | {[_ModerationStatus, 0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [46] | {[InstanceID, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [47] | {[Order, 980400]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [48] | {[GUID, 1628ce93-e57f-48bd-b1d7-79dde939d9bc]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [49] | {[WorkflowInstanceID, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [50] | {[FileRef, /teams/physsec/Lists/RoB Tasks/9804_.000]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [51] | {[FileDirRef, /teams/physsec/Lists/RoB Tasks]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [52] | {[Last_x0020_Modified, 2017-06-27T18:27:53Z]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [53] | {[Created_x0020_Date, 2017-06-27T18:27:53Z]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [54] | {[FSObjType, 0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [55] | {[SortBehavior, Microsoft.SharePoint.Client.FieldLookupValue]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [56] | {[FileLeafRef, 9804_.000]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [57] | {[UniqueId, deee7386-6e54-482c-b96a-52c29d0d185b]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [58] | {[SyncClientId, Microsoft.SharePoint.Client.FieldLookupValue]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [59] | {[ProgId, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [60] | {[ScopeId, {6EA468AC-9BDE-4114-A10E-259D7BA33B65}]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [61] | {[MetaInfo, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [62] | {[_Level, 1]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [63] | {[_IsCurrentVersion, True]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [64] | {[ItemChildCount, 0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [65] | {[FolderChildCount, 0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [66] | {[Restricted, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [67] | {[OriginatorId, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [68] | {[NoExecute, 0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [69] | {[ContentVersion, 0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [70] | {[_ComplianceFlags, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [71] | {[_ComplianceTag, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [72] | {[_ComplianceTagWrittenTime, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [73] | {[_ComplianceTagUserId, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [74] | {[AccessPolicy, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [75] | {[_VirusStatus, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [76] | {[_VirusVendorID, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [77] | {[_VirusInfo, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [78] | {[AppAuthor, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [79] | {[AppEditor, ]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [80] | {[SMTotalSize, Microsoft.SharePoint.Client.FieldLookupValue]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [81] | {[SMLastModifiedDate, 2017-06-28T11:35:39Z]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [82] | {[SMTotalFileStreamSize, 0]} | System.Collections.Generic.KeyValuePair<string,   object>
+ |   | [83] | {[SMTotalFileCount, Microsoft.SharePoint.Client.FieldLookupValue]} | System.Collections.Generic.KeyValuePair<string,   object>

**Stack Trace for the Error**
--
at   Microsoft.FSharp.Core.Operators.FailWith[T](String message)
at   Holm.SPCalendarRecurrenceExpander.Parser.parseRecurrence(Dictionary`2 d) in   C:\Users\rh\Source\Repos\SPCalendarRecurrenceExpander\Src\SPCalendarRecurrenceExpander\Parser.fs:line   209
at Holm.SPCalendarRecurrenceExpander.Parser.parse(Dictionary`2 a) in   C:\Users\rh\Source\Repos\SPCalendarRecurrenceExpander\Src\SPCalendarRecurrenceExpander\Parser.fs:line   223
at Holm.SPCalendarRecurrenceExpander.Parser.Parse(Dictionary`2   appointment) in   C:\Users\rh\Source\Repos\SPCalendarRecurrenceExpander\Src\SPCalendarRecurrenceExpander\Parser.fs:line   230
at   <StartupCode$SPCalendarRecurrenceExpander>.$Expander.tzCorrectedAppointments@40.Invoke(Dictionary`2   a) in   C:\Users\rh\Source\Repos\SPCalendarRecurrenceExpander\Src\SPCalendarRecurrenceExpander\Expander.fs:line   40
at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2   mapping, FSharpList`1 x)
at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2   mapping, FSharpList`1 list)
at   Holm.SPCalendarRecurrenceExpander.CalendarRecurrenceExpander.Expand(List`1   appointments) in   C:\Users\rh\Source\Repos\SPCalendarRecurrenceExpander\Src\SPCalendarRecurrenceExpander\Expander.fs:line   36
at RoBDailyReminderSMTP.Program.SendEmail(ListItemCollection   listItemColl) in F:\TFS\SPO Migration\Build\Solutions\RoBDailyReminder -SMTP   EMAIL\RoBDailyReminder\Program.cs:line 236

**Comment by ronnieholm** [comment]
It seems "explicit end" didn't parse. For a recurrence appointment that's the date and time on which the series ends. In the example data, I see "EndDate, 11/1/2016 5:00:00 PM" which looks good to me. I wonder if some other item is causing the issue?

I appears you're doing a SharePoint migration. Which version of SharePoint did you migrate from? It should work with any version as the recurrence logic hasn't change for a very long time. But could be there's some corner case with very old SharePoint versions.

**Comment by ujwalseli** [comment]
We did a migration from 2013 on-premises to SharePoint online, i am quite sure that this is the item causing the issue as I had to break the collection and then call expander.expand in batches to identify the culprit.
 Data for other records which are failing have similar recurrence pattern and difference in Start time and End time was only 1 hour for all records. I explicitly tried setting up a 1 year difference between start and End date but that too didn't help.

**Comment by ronnieholm** [comment]
Would it be possible for you to save the list as a template, including data, and mail it to me at mail@bugfree.dk? I should be able to import the list in my SPO tenant. If that's not too much work on your part having to anonymize content.

**Comment by ujwalseli** [comment]
I may not be able to share the original list with you but I will try to replicate the issue on dummy list and share that.

**Comment by ronnieholm** [comment]
Closing this one. Reopen if you have an export or more specific repro.
