### ISSUE TITLE
Weekly Recurring event with more then 1 recur week fetching wrong data

### ISSUE THREAD

**Issue by Vaibhav100786** [ronnieholm/SPCalendarRecurrenceExpander#18]
![cal1](https://user-images.githubusercontent.com/39090962/39760404-d5d2be82-52f2-11e8-984b-de2361f21e3e.png)

I have create one recurring event with recur every 2 week.I have attach screen shot.
So as per event it should get event one after another sunday. like if first event is on 6/5/2018 then second event should be 20/5/2018 and so on.

But it is getting event for every sunday.
 
Recurrence Data is given below.
`<recurrence><rule><firstDayOfWeek>su</firstDayOfWeek><repeat><weekly su="TRUE" weekFrequency="2" /></repeat><repeatInstances>10</repeatInstances></rule></recurrence>`

Is this a bug or is there any other way to get weekly recur event?

Thanks

**Comment by ronnieholm** [comment]
Hi Vaibhav. Thank you for reporting. It sounds like a bug. I haven't got access to a SharePoint environment these days so I can't verify and fix. I'll have to defer until the next time I have SharePoint access.

**Comment by ronnieholm** [comment]
Closing. Probably no one is using this library anymore.
