### ISSUE TITLE
testing uncovered exception in a Daily recurrence

### ISSUE THREAD

**Issue by thomasbtatum** [ronnieholm/SPCalendarRecurrenceExpander#2]
With my testing, when you create a Daily recurrence event with certain conditions, you get an F3 exception in the find method.

The certain conditions are:
1) Daily recurrence has to be every weekday and 
2) the event must stretch across 1 or more months

The exception happens at the call:
Find[T]
nextWeekDay (Compiler.fs line 98)

I am using SharePoint 2010 and CSOM to collect the calendar event.  Once I pass this to the SPCalendarRecurrenceExpander - I get the exception.

**Comment by ronnieholm** [comment]
Thanks for taking the time to report your findings.
Could you please provide a complete stack trace and the exact properties of the calendar item (perhaps a screenshot)?
I cannot reproduce from conditions (1) and (2) alone.

**Comment by ronnieholm** [comment]
I managed to reproduce a similar stack trace. 
It happens when 
(1) daily recurrence is every weekday and
(2) appointment stretch across a month where the last day of the month is a weekend day, such as Sat, Oct 31, 2015 and Sun, Nov 1, 2015.

**Comment by ronnieholm** [comment]
Please try out SPCalendarRecurrenceExpander, version 1.0.2 on NuGet. It should fix your issue.

**Comment by thomasbtatum** [comment]
Works great.  Thank you.
