### ISSUE TITLE
Pulling back data from list gives "System.Exception: 'a.start and a.end'

### ISSUE THREAD

**Issue by Method-Development** [ronnieholm/SPCalendarRecurrenceExpander#20]
So if I run:

`    
        using (var cc = new AuthenticationManager().GetAppOnlyAuthenticatedContext(siteUrl, appId, appSecret))
            {
                cc.Load(cc.Web, p => p.Title);
                cc.Load(cc.Web.Lists);
                cc.Load(cc.Web.RegionalSettings.TimeZone);
                cc.ExecuteQuery();

                var tz = cc.Web.RegionalSettings.TimeZone;
                foreach (var list in cc.Web.Lists.Where(e => e.Title == "My Calendar"))
                {
                    CamlQuery cQuery = new CamlQuery();

                    ListItemCollection colListItem = list.GetItems(cQuery);
                    cc.Load(colListItem);
                    cc.ExecuteQuery();

                    var collapsedAppointments = colListItem.ToList().Select(i => i.FieldValues).ToList();
                    var expander = new CalendarRecurrenceExpander(
                            tz.Information.Bias,
                            tz.Information.DaylightBias
                        );

                }

                //ViewBag.test = derp;
            };
            return View();`

it works but the minute I go to expand it using:

`var recurrenceInstances = expander.Expand(collapsedAppointments);`

I get the error "System.Exception:'a.start and a.end'"

**Comment by ronnieholm** [comment]
Do you have a stack trace?

**Comment by Method-Development** [comment]
> Do you have a stack trace?

`
"   at Microsoft.FSharp.Core.Operators.FailWith[T](String message) in F:\\workspace\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\prim-types.fs:line 3293\r\n   at Holm.SPCalendarRecurrenceExpander.Compiler.Compile(Appointment a, FSharpList`1 deletedRecurrences, FSharpList`1 recurrenceExceptions) in C:\\Users\\rh\\Source\\Repos\\SPCalendarRecurrenceExpander\\Src\\SPCalendarRecurrenceExpander\\Compiler.fs:line 151\r\n   at <StartupCode$SPCalendarRecurrenceExpander>.$Expander.expandedAppointments@77.Invoke(Appointment a) in C:\\Users\\rh\\Source\\Repos\\SPCalendarRecurrenceExpander\\Src\\SPCalendarRecurrenceExpander\\Expander.fs:line 88\r\n   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) in F:\\workspace\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\local.fs:line 241\r\n   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in F:\\workspace\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\local.fs:line 251\r\n   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in F:\\workspace\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\list.fs:line 75\r\n   at Holm.SPCalendarRecurrenceExpander.CalendarRecurrenceExpander.Expand(List`1 appointments) in C:\\Users\\rh\\Source\\Repos\\SPCalendarRecurrenceExpander\\Src\\SPCalendarRecurrenceExpander\\Expander.fs:line 75\r\n   at SPO_RecurringEvent.Controllers.apiController.Test(String siteUrl, String appId, String appSecret)\r\n   at SPO_RecurringEvent.Controllers.apiController.Index()\r\n   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)\r\n   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()"
`

this is what I get

I am able to run

`
 using (var cc = new AuthenticationManager().GetAppOnlyAuthenticatedContext(siteUrl, appId, appSecret))
            {
                cc.Load(cc.Web, p => p.Title);
                cc.Load(cc.Web.Lists);
                cc.Load(cc.Web.RegionalSettings.TimeZone);
                cc.ExecuteQuery();

                var tz = cc.Web.RegionalSettings.TimeZone;
                foreach (var list in cc.Web.Lists.Where(e => e.Title == "My Calendar"))
                {
                    CamlQuery cQuery = new CamlQuery();

                    ListItemCollection colListItem = list.GetItems(cQuery);
                    cc.Load(colListItem);
                    cc.ExecuteQuery();
                    string testing = null;
                    var collapsedAppointments = colListItem.ToList().Select(i => i.FieldValues).ToList();
                    var expander = new CalendarRecurrenceExpander(
                            tz.Information.Bias,
                            tz.Information.DaylightBias
                            
                        );

                    //var recurrenceInstances = expander.Expand(collapsedAppointments);

                    foreach(var item in colListItem)
                    {
                        testing += item.Id;
                    }
                    var recurrenceInstances = expander.Expand(collapsedAppointments);
                    ViewBag.test = testing;
                }

                
            };
`

and I get all the IDs so I am able to access the list. If it helps this is a large calendar.

also thanks for actually responding! :)

**Comment by ronnieholm** [comment]
I'm not sure how it's possible, but it appears you have an appointment with start date >= end date.

It's been a while since I wrote the code. If SharePoint does indeed allow zero duration events, as the comment claims, I wonder why the check isn't start > end:

``` fsharp
// SharePoint allows events with start = end => 0 duration
if a.Start >= a.End then failwith "a.start and a.end"
```

**Comment by Method-Development** [comment]
> I'm not sure how it's possible, but it appears you have an appointment with start date >= end date.
> 
> It's been a while since I wrote the code. If SharePoint does indeed allow zero duration events, as the comment claims, I wonder why the check isn't start > end:
> 
> ```fsharp
> // SharePoint allows events with start = end => 0 duration
> if a.Start >= a.End then failwith "a.start and a.end"
> ```

Odd, wonder where that entry is... I will sift through it. Is there anything I can change to actively account for that?

**Comment by ronnieholm** [comment]
It's a bit of a challenge if it's a large existing calendar and you can't delete items to identify the offending one. There's an `Expander.Dump(...)` method that dumps the calendar pattern in parsed form. But if the calendar has many kinds of appointment that's overwhelming and not particularly helpful.

**Comment by Method-Development** [comment]
> It's a bit of a challenge if it's a large existing calendar and you can't delete items to identify the offending one. There's an `Expander.Dump(...)` method that dumps the calendar pattern in parsed form. But if the calendar has many kinds of appointment that's overwhelming and not particularly helpful.

I found the entries and am adjusting the 10 of them... holy hell how do people manage to do that. Thanks!

**Comment by ronnieholm** [comment]
Did you encounter an appointment with start = end, meaning zero duration?

**Comment by Method-Development** [comment]
> Did you encounter an appointment with start = end, meaning zero duration?

They made events where the start time was equal to the end time. I am clearing those now and them am going to test.

**Comment by ronnieholm** [comment]
So the code comment was actually right -- SharePoint does support zero duration appointments -- and the if condition is wrong. Good to know :D

**Comment by Method-Development** [comment]
> So the code comment was actually right -- SharePoint does support zero duration appointments -- and the if condition is wrong. Good to know :D

Yup, that seems like it was the issue. Only downside is the JSON is way longer than I had hoped for hitting the maxJsonLength lol

**Comment by ronnieholm** [comment]
You may be able to implement paging in your client code, then call the calendar expander multiple times, and manually combine the results.
