### ISSUE TITLE
Suggestion: Provide optional start/end dates for expansion process

### ISSUE THREAD

**Issue by Trailbear** [ronnieholm/SPCalendarRecurrenceExpander#4]
I suggest that the Expander optionally return only instances within a date range.

I find that my users like to create events that are perpetual, using the option "no end date".  This is for a group that has monthly meetings in a predictable pattern.  So first Monday at 7:00pm, forever.

The result when expanding this type of series is one appointment a month from the start of the series out to the year 2098.  That is a lot of Instances (about 900 per appointment) that are way out of range of any normal calendar.   

If the Expander took optional start and end parameters, then it could save a lot of processing.  Albeit not really a huge amount of time or memory since RecurrenceInstance is a very lightweight object.  But that leads me to another suggestion.  But rather than muddle the two suggestions together here, I will offer that suggestion separately.

-TrailBear 
Frank Long

**Comment by ronnieholm** [comment]
Good point. SharePoint defaults to 999 instances if no explicit end date is provided. It can take some time (100+ milliseconds) to resolve some types of appointments with no explicit end dates. If one had many such appointments in the calendar, such a start/end range could provide a significant speedup.

**Comment by ronnieholm** [comment]
Closing. Probably no one is using this library anymore.
