### ISSUE TITLE
Scenario: Accessing FieldValues for Recurrence Exceptions is straightforward

### ISSUE THREAD

**Issue by Trailbear** [ronnieholm/SPCalendarRecurrenceExpander#5]
In the example code, the FieldValues Dictionary used to populate the title is always the first or master appointment.  The expander applies date updates appropriately.  However other properties can be altered in the user interface, not to mention custom columns (we have a couple). To maintain these edits the code needs to access the values from the exception appointment as opposed to the series master appointment.  

It seems like there _should_ be a way to find the exception appointment for a given instance's ID and date, if one exists, and use that appointment instead of the master.  But I am unsure how to code this in a lambda function.  I have a feeling that it would end up being a bit cryptic in any case.  Seemingly a good candidate for putting that logic into the assembly if everyone will end up having to do it.

If there is no limit on how many instances are created and there are no exceptions, then copying the rather weighty dictionary onto the instance before converting to a domain object seems wasteful.  However where start and end dates are provided (Issue #4), the number of instances won't be any larger than a properly expanded result set from SharePoint.  

My initial preference was to see the FieldValues dictionary added to each RecurrenceInstance.  By providing the entire dictionary any custom columns are maintained along with changes that may be part of the exception appointment.  If it is on every Instance, the process of converting to a domain object becomes a simple mapping exercise.

-TrailBear
Frank Long

**Comment by ronnieholm** [comment]
You're good at spotting edge cases. I appreciate it :)

I wasn't aware each exception could have a unique Title for instance. Will take an extra look at the UI in the next couple of days and correlate with FieldValues.

Also, I see the point about the mapping and I follow the argument that it's more of an internal thing than something every user should be bothered with.

**Comment by ronnieholm** [comment]
Closing. Probably no one is using this library anymore.
